# Generated by Django 3.2.3 on 2021-09-14 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery', '0002_delete_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery_Item_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery_item', models.CharField(max_length=100)),
                ('cost_price', models.IntegerField()),
                ('added_date', models.DateTimeField()),
                ('selling_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bakery_item_recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(blank=True, null=True)),
                ('bakery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.bakery_item_names')),
            ],
        ),
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=15)),
                ('quantity_added', models.IntegerField(blank=True, null=True)),
                ('added_date', models.DateTimeField()),
                ('price_per_unit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True)),
                ('order_time', models.TimeField(auto_now=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('bakery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.bakery_item_recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bakery_item_recipe',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.ingredients'),
        ),
    ]
