# Generated by Django 3.2.3 on 2021-09-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_alter_ingredients_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery_item_names',
            name='bakery_item',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
