# Generated by Django 3.2.3 on 2021-09-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_alter_bakery_item_names_bakery_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
