# Generated by Django 3.2.3 on 2021-09-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_alter_ingredients_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery_item_names',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
