# Generated by Django 3.2.3 on 2021-09-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_alter_bakery_item_names_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bakery_item_names',
            old_name='selling_price',
            new_name='price',
        ),
    ]
