# Generated by Django 3.2.3 on 2021-09-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0008_rename_selling_price_bakery_item_names_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='bakery_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.bakery_item_names'),
        ),
    ]
