# Generated by Django 3.2.3 on 2021-09-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0011_bakery_item_names_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bakery_item_names',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
