# Generated by Django 3.2.3 on 2021-09-17 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0012_alter_bakery_item_names_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakery_item_names',
            name='discount',
        ),
    ]
